### ISSUE TITLE
Matplotlib Example Fails - sys.argv

### ISSUE THREAD

**Issue by wilsoniain** [ylikx/forpy#22]
I have built matplotlib example using Code Blocks and MinGW64 on Windows 10. This generates below error. Other provided examples build and run without issue. 

`Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 2761, in plot
    return gca().plot(
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 879, in gca
    return gcf().gca(**kwargs)
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 611, in gcf
    return figure()
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 546, in figure
    **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\backend_bases.py", line 3337, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\backends\_backend_tk.py", line 876, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "C:\Program Files\Python37\Lib\tkinter\__init__.py", line 2018, in __init__
    baseName = os.path.basename(sys.argv[0])
IndexError: list index out of range`

I believe this is related to tkinter expecting sys.argv as detailed here:

https://github.com/matplotlib/matplotlib/issues/14382

Could anyone advise how best to resolve this when using forpy?

**Comment by ylikx** [comment]
Hi, are you using the most recent forpy? This issue should be fixed already (see issue #15).

**Comment by wilsoniain** [comment]
Hi, firstly, apologies, I didn't see closed issues tab - I'm fairly new to using github.

But regarding the sys.argv issue, yes, I'm using latest version of forpy_mod.F90. I can also see "function forpy_initialize_sys_argv()" in the code, which I assume is confirmation of this. I've rebuilt just now and issue is still present.

I note from the comments, that python 3.8 had a fix for this. I can confirm, I using python 3.8, the issue is no longer present.

**Comment by ylikx** [comment]
No problem, it seems that my fix is incomplete. I guess that your `sys.argv == []`.
You can check that by printing sys.argv:
`ierror = run_string("import sys;print(sys.argv)")`

**Comment by ylikx** [comment]
I have pushed a new commit to the repo, does it fix the issue for your platform?

**Comment by wilsoniain** [comment]
Yes, that's working now. 

Thanks for the help.

**Comment by ylikx** [comment]
Thanks for bringing this issue to my attention!
